import React, { useState, useEffect } from "react";
import Carousel from "../../../components/carousel/Carousel";
import ContentWrapper from "../../../components/contentWrapper/ContentWrapper";
import SwitchTabs from "../../../components/switchTabs/SwitchTabs";
import { HiOutlineFilm, HiUser  } from "react-icons/hi";
import { MdOutlineSportsCricket } from "react-icons/md";
import { FaBusinessTime } from "react-icons/fa";
import { GiCardJoker } from "react-icons/gi";
import { MdOutlineTv } from "react-icons/md";
import { GiLoveSong } from "react-icons/gi";
import { SlPeople } from "react-icons/sl";
import { HiOutlineSwitchHorizontal } from "react-icons/hi";
import { HiOutlineUserGroup } from "react-icons/hi";
import { FaFemale } from "react-icons/fa";

import './trending.scss';

const Trending = () => {


const sampleData1 = {
  page: 1,
  results: [
    {
      "adult": false,
      "backdrop_path": "/qtyucfno7a3j8kfttzm5.jpg",
      "genre_ids": [1],
      "id": 900000,
      "media_type": "movie",
      "position": "comedy_actor",
      "original_language": "en",
      "original_title": "Sadhu kokila",
      "overview": "Several generations following Caesar's reign, apes – now the dominant species – live harmoniously while humans have been reduced to living in the shadows. As a new tyrannical ape leader builds his empire, one young ape undertakes a harrowing journey that will cause him to question all he's known about the past and to make choices that will define a future for apes and humans alike.",
      "popularity": 3116.984,
      "poster_path": "/qtyucfno7a3j8kfttzm5.jpg",
      "release_date": "2024-05-08",
      "title": "Sadhu Kokila",
      "video": false,
      "vote_average": 6.935,
      "vote_count": 1440
    },
    {
      "adult": false,
      "backdrop_path": "/uu4bvj8knkzhtfps080r.jpg",
      "genre_ids": [1],
      "id": 900001,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "Sudeep",
      "overview": "An apocalyptic story set in the furthest reaches of our planet, in a stark desert landscape where humanity is broken, and most everyone is crazed fighting for the necessities of life. Within this world exist two rebels on the run who just might be able to restore order.",
      "popularity": 2804.235,
      "poster_path": "/uu4bvj8knkzhtfps080r.jpg",
      "release_date": "2015-05-15",
      "title": "Sudeep",
      "video": false,
      "vote_average": 7.582,
      "vote_count": 18564
    },
    {
      "adult": false,
      "backdrop_path": "/iy4fuxmsnsh3izz0beqt.jpg",
      "genre_ids": [3],
      "id": 900002,
      "media_type": "movie",
      "position": "singer",
      "original_language": "en",
      "original_title": "Singer",
      "overview": "The last Gunslinger, Roland Deschain, has been locked in an eternal battle with Walter O'Dim, also known as the Man in Black, determined to prevent him from toppling the Dark Tower, which holds the universe together. With the fate of the worlds at stake, good and evil will collide in the ultimate battle as only Roland can defend the Tower from the Man in Black.",
      "popularity": 1624.289,
      "poster_path": "/iy4fuxmsnsh3izz0beqt.jpg",
      "release_date": "2017-08-03",
      "title": "Vijay Prakash",
      "video": false,
      "vote_average": 5.7,
      "vote_count": 3542
    },
    {
      "adult": false,
      "backdrop_path": "/nre86tonrixcrckv4ncv.jpg.jpg",
      "genre_ids": [3],
      "id": 900003,
      "media_type": "movie",
      "position": "singer",
      "original_language": "en",
      "original_title": "singer",
      "overview": "When the Justice League meets members of the Justice Society of America, they join forces to combat a powerful new threat in the midst of World War II.",
      "popularity": 1204.211,
      "poster_path": "/nre86tonrixcrckv4ncv.jpg",
      "release_date": "2021-04-27",
      "title": "Sonu Neegam",
      "video": false,
      "vote_average": 7.7,
      "vote_count": 153
    },
    {
      "adult": false,
      "backdrop_path": "/rishab_shetty_xclwgj.jpg", 
      "genre_ids": [1],
      "id": 900077,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/rishab_shetty_xclwgj.jpg",
      "release_date": "2016-01-13",
      "title": "Rishab Shetty",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/fudEG1VUWuOqleXv6NwCExK0VLy.jpg",
      "genre_ids": [3],
      "id": 900004,
      "media_type": "movie",
      "position": "singer",
      "original_language": "en",
      "original_title": "Singer",
      "overview": "Jonathan Kent and reluctant young sidekick Damian Wayne are burdened with saving the world from impending doom. The two must join forces to rescue their fathers and save the planet by becoming the super heroes they were intended to be.",
      "popularity": 955.684,
      "poster_path": "/oa12vinwzhfhg69ortbb.jpg",
      "release_date": "2022-10-18",
      "title": "Ragu Deekshith",
      "video": false,
      "vote_average": 7.7,
      "vote_count": 162
    },
    {
      "adult": false,
      "backdrop_path": "/oE6bhqqVFyIECtBzqIuvh6JdaB5.jpg",
      "genre_ids": [9],
      "id": 900005,
      "media_type": "movie",
      "position": "comedy_actor",
      "original_language": "en",
      "original_title": "Toy Story 4",
      "overview": "Woody has always been confident about his place in the world and that his priority is taking care of his kid, whether that's Andy or Bonnie. But when Bonnie adds a reluctant new toy called Forky to her room, a road trip adventure alongside old and new friends will show Woody how big the world can be for a toy.",
      "popularity": 1424.139,
      "poster_path": "/xuxmsni79p4olmfkcejn.jpg",
      "release_date": "2019-06-21",
      "title": "Doddanna",
      "video": false,
      "vote_average": 7.6,
      "vote_count": 7106
    },
    {
      "adult": false,
      "backdrop_path": "/lcq8dVxeeOqHvvgcte707K0KVx5.jpg",
      "genre_ids": [9],
      "id": 900006,
      "media_type": "movie",
      "position": "comedy_actor",
      "original_language": "en",
      "original_title": "Tenet",
      "overview": "Armed with only one word – Tenet – and fighting for the survival of the world, a Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.",
      "popularity": 2126.348,
      "poster_path": "/ebrdo9ekskwfuc9buf1j.jpg",
      "release_date": "2020-08-22",
      "title": "Chikkanna",
      "video": false,
      "vote_average": 7.2,
      "vote_count": 7198
    },
    {
      "adult": false,
      "backdrop_path": "/rashmika_mandana_lrw2qx.jpg", 
      "genre_ids": [2],
      "id": 900054,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/rashmika_mandana_lrw2qx.jpg",
      "release_date": "2016-01-13",
      "title": "Rashmika Mandanna",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/u1vpmfedlt3xknegum6t.png",
      "genre_ids": [1],
      "id": 900007,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/u1vpmfedlt3xknegum6t.png",
      "release_date": "2016-01-13",
      "title": "Shivraj Kumar",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/rukmini-vasanth_zsrrde.jpg", 
      "genre_ids": [2],
      "id": 900053,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/rukmini-vasanth_zsrrde.jpg",
      "release_date": "2016-01-13",
      "title": "Rukmini Vasanth",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/yash_s6aw8h.jpg",
      "genre_ids": [1],
      "id": 900008,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/yash_s6aw8h.jpg",
      "release_date": "2016-01-13",
      "title": "Yash ",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/s5mbdtyweqk1ezejsxyl.jpg",
      "genre_ids": [1],
      "id": 900023,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/s5mbdtyweqk1ezejsxyl.jpg",
      "release_date": "2016-01-13",
      "title": "Ramesh Arvind",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/wo9sSrxHK7Eo7APY6BNiPqH0uQs.jpg",
      "genre_ids": [1],
      "id": 900010,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "The Patriot",
      "overview": "After proving himself on the field of battle in the French and Indian War, Benjamin Martin wants nothing more to do with such things, preferring the simple life of a farmer. But when his son Gabriel enlists in the army to defend their new nation, America, against the British, Benjamin reluctantly returns to his old life to protect his son.",
      "popularity": 1421.593,
      "poster_path": "/bsohekiuwfvnwf1g791m.jpg",
      "release_date": "2000-06-28",
      "title": "Diganth M",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2440
    },
    {
      "adult": false,
      "backdrop_path": "/suw8eyL3YwE4wfzPQ0lAKyA3LfP.jpg",
      "genre_ids": [4],
      "id": 900013,
      "media_type": "movie",
      "position": "anchor",
      "original_language": "en",
      "original_title": "F9",
      "overview": "Dominic Toretto and his crew join forces to battle the most skilled assassin and high-performance driver they've ever encountered – his forsaken brother.",
      "popularity": 1632.48,
      "poster_path": "/cxcpnwh5fockax1f9whn.jpg",
      "release_date": "2021-05-19",
      "title": "Akul Balaji",
      "video": false,
      "vote_average": 6.8,
      "vote_count": 4734
    },
    {
      "adult": false,
      "backdrop_path": "/wokh9gbagoxu2vprwyx1.jpg",
      "genre_ids": [3],
      "id": 900014,
      "media_type": "movie",
      "position": "singer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/wokh9gbagoxu2vprwyx1.jpg",
      "release_date": "2016-01-13",
      "title": "Shreya Goshal",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/wokh9gbagoxu2vprwyx1.jpg",
      "genre_ids": [4],
      "id": 900015,
      "media_type": "movie",
      "position": "anchor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/ehtac9cheylg3gwtjzxp.jpg",
      "release_date": "2016-01-13",
      "title": "Anushree ",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/mlt9fvwaitq8o1ratq45.jpg",
      "genre_ids": [4],
      "id": 900016,
      "media_type": "movie",
      "position": "anchor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/mlt9fvwaitq8o1ratq45.jpg",
      "release_date": "2016-01-13",
      "title": "Srujan Lokesh ",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/klijsfjfn6lebwyw1d20.jpg",
      "genre_ids": [2],
      "id": 900017,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/klijsfjfn6lebwyw1d20.jpg",
      "release_date": "2016-01-13",
      "title": "Milana Nagaraj ",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/chpbzonooanclo0nfldo.jpg",
      "genre_ids": [2],
      "id": 900019,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/chpbzonooanclo0nfldo.jpg",
      "release_date": "2016-01-13",
      "title": "Rachita Ram",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/efaygyfatcmw91tlfahv.jpg",
      "genre_ids": [1],
      "id": 900020,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/efaygyfatcmw91tlfahv.jpg",
      "release_date": "2016-01-13",
      "title": "Upendra",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/q8zqn3hwwgnpzmgkyl3h.jpg",
      "genre_ids": [1],
      "id": 900021,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/q8zqn3hwwgnpzmgkyl3h.jpg",
      "release_date": "2016-01-13",
      "title": "Ganesh",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/q6uqnp3i5zfcrmklwyih.jpg",
      "genre_ids": [3],
      "id": 900027,
      "media_type": "movie",
      "position": "singer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/q6uqnp3i5zfcrmklwyih.jpg",
      "release_date": "2016-01-13",
      "title": "Naditha",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/cohje0ntvlh0yeu5sktw.jpg",
      "genre_ids": [9],
      "id": 900029,
      "media_type": "movie",
      "position": "comedy_actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/cohje0ntvlh0yeu5sktw.jpg",
      "release_date": "2016-01-13",
      "title": "Komal",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/sbiddsc3y5ykrxmzarng.jpg",
      "genre_ids": [9],
      "id": 900030,
      "media_type": "movie",
      "position": "comedy_actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/sbiddsc3y5ykrxmzarng.jpg",
      "release_date": "2016-01-13",
      "title": "Rangayana Raghu",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/anil_kumble_rkwafv.jpg",
      "genre_ids": [7],
      "id": 900031,
      "media_type": "movie",
      "position": "sports",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/anil_kumble_rkwafv.jpg",
      "release_date": "2016-01-13",
      "title": "Anil Kumble",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/rabin_utappa_n9h2py.png",
      "genre_ids": [7],
      "id": 900032,
      "media_type": "movie",
      "position": "sports",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/rabin_utappa_n9h2py.png",
      "release_date": "2016-01-13",
      "title": "Rabin Uthappa",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/shreyanka_patil_bxh4gv.jpg",
      "genre_ids": [7],
      "id": 900033,
      "media_type": "movie",
      "position": "sports",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/shreyanka_patil_bxh4gv.jpg",
      "release_date": "2016-01-13",
      "title": "Shreyanka Patil",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/varsha_rohit_rndhjr.jpg",
      "genre_ids": [7],
      "id": 900034,
      "media_type": "movie",
      "position": "sports",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/varsha_rohit_rndhjr.jpg",
      "release_date": "2016-01-13",
      "title": "Varsha Rohit",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/veda_krishnamurthy_zetnyf.jpg",
      "genre_ids": [7],
      "id": 900035,
      "media_type": "movie",
      "position": "sports",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/veda_krishnamurthy_zetnyf.jpg",
      "release_date": "2016-01-13",
      "title": "Veda Krishna Murthy",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/sudhamurthy_ntrfd6.jpg",
      "genre_ids": [5],
      "id": 900036,
      "media_type": "movie",
      "position": "enterprenuer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/sudhamurthy_ntrfd6.jpg",
      "release_date": "2016-01-13",
      "title": "Sudha Murthy",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/sharan_hegde_oql1cn.jpg",
      "genre_ids": [5],
      "id": 900037,
      "media_type": "movie",
      "position": "enterprenuer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/sharan_hegde_oql1cn.jpg",
      "release_date": "2016-01-13",
      "title": "Sharan Hegde",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/archana_fcpw4v.jpg",
      "genre_ids": [8],
      "id": 900038,
      "media_type": "movie",
      "position": "influencer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/archana_fcpw4v.jpg",
      "release_date": "2016-01-13",
      "title": "Archana",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/Sudhir-Shivaram_vldobm.jpg",
      "genre_ids": [8],
      "id": 900039,
      "media_type": "movie",
      "position": "influencer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/Sudhir-Shivaram_vldobm.jpg",
      "release_date": "2016-01-13",
      "title": "Sudheer",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/hemalatha_u2itix.jpg",
      "genre_ids": [8],
      "id": 900040,
      "media_type": "movie",
      "position": "influencer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/hemalatha_u2itix.jpg",
      "release_date": "2016-01-13",
      "title": "Hemlatha",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/jordindian_olhz9a.jpg",
      "genre_ids": [8],
      "id": 900041,
      "media_type": "movie",
      "position": "influencer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/jordindian_olhz9a.jpg",
      "release_date": "2016-01-13",
      "title": "Jordindian",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/kavya_karnatak_yqjppe.jpg",
      "genre_ids": [8],
      "id": 900042,
      "media_type": "movie",
      "position": "influencer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/kavya_karnatak_yqjppe.jpg",
      "release_date": "2016-01-13",
      "title": "Kavya",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/neha_chathlani_fcaceo.jpg",
      "genre_ids": [8],
      "id": 900043,
      "media_type": "movie",
      "position": "influencer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/neha_chathlani_fcaceo.jpg",
      "release_date": "2016-01-13",
      "title": "Neha Chatlani",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/ariya_hegde_laq3p5.jpg",
      "genre_ids": [8],
      "id": 900044,
      "media_type": "movie",
      "position": "influencer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/ariya_hegde_laq3p5.jpg",
      "release_date": "2016-01-13",
      "title": "Ariya Hegde",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/nikhil_chinnappa_jkzawa.jpg",
      "genre_ids": [6],
      "id": 900045,
      "media_type": "movie",
      "position": "fitness",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/nikhil_chinnappa_jkzawa.jpg",
      "release_date": "2016-01-13",
      "title": "Nikhil Chinappa",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/adithi_prabudeva_ief5ol.jpg",
      "genre_ids": [2],
      "id": 900046,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/adithi_prabudeva_ief5ol.jpg",
      "release_date": "2016-01-13",
      "title": "Adhithi Prabhudeva",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/advithi_shetty_fegjol.jpg",
      "genre_ids": [2],
      "id": 900047,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/advithi_shetty_fegjol.jpg",
      "release_date": "2016-01-13",
      "title": "Advithi Shetty",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/aindritha_ray_vputeg.jpg",
      "genre_ids": [2],
      "id": 900048,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/aindritha_ray_vputeg.jpg",
      "release_date": "2016-01-13",
      "title": "Sindhritha Ray",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/ajay-rao_mok7mc.jpg", 
      "genre_ids": [1],
      "id": 900049,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/ajay-rao_mok7mc.jpg",
      "release_date": "2016-01-13",
      "title": "Ajay Rao",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/cqbo8atfrkohiyx7vd4n.jpg",
      "genre_ids": [2],
      "id": 900018,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/cqbo8atfrkohiyx7vd4n.jpg",
      "release_date": "2016-01-13",
      "title": "Sanjana Ananad",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/amulya_pkz33t.jpg", 
      "genre_ids": [2],
      "id": 900050,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/amulya_pkz33t.jpg",
      "release_date": "2016-01-13",
      "title": "Amulya",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/anupama_anandkumar_hjv3az.jpg", 
      "genre_ids": [2],
      "id": 900051,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/anupama_anandkumar_hjv3az.jpg",
      "release_date": "2016-01-13",
      "title": "Anupama Anand Kumar",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/anuprabhakar_v5f8my.jpg", 
      "genre_ids": [2],
      "id": 900052,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/anuprabhakar_v5f8my.jpg",
      "release_date": "2016-01-13",
      "title": "Anu Prabhakar",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/pooja_hegde_e8qo3x.jpg", 
      "genre_ids": [2],
      "id": 900055,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/pooja_hegde_e8qo3x.jpg",
      "release_date": "2016-01-13",
      "title": "Pooja Hegde",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/haripriya_nhpjko.jpg", 
      "genre_ids": [2],
      "id": 900056,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/haripriya_nhpjko.jpg",
      "release_date": "2016-01-13",
      "title": "Haripriya",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/chaithra-latha_cigrix.jpg", 
      "genre_ids": [2],
      "id": 900057,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/chaithra-latha_cigrix.jpg",
      "release_date": "2016-01-13",
      "title": "Chaithra Latha",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/sapthami_gowda_nbqgg2.jpg", 
      "genre_ids": [2],
      "id": 900058,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/sapthami_gowda_nbqgg2.jpg",
      "release_date": "2016-01-13",
      "title": "Sapthami Gowda",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/namratha_gowda_gawinl.jpg", 
      "genre_ids": [2],
      "id": 900059,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/namratha_gowda_gawinl.jpg",
      "release_date": "2016-01-13",
      "title": "Namratha Gowda",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/samyuktha_hegde_vkvrie.jpg", 
      "genre_ids": [2],
      "id": 900060,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/samyuktha_hegde_vkvrie.jpg",
      "release_date": "2016-01-13",
      "title": "Samyuktha Hegde",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/disha_madana_bx5vg3.jpg", 
      "genre_ids": [2],
      "id": 900061,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/disha_madana_bx5vg3.jpg",
      "release_date": "2016-01-13",
      "title": "Disha Mandana",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/meghna_raj_hw6gdw.jpg", 
      "genre_ids": [2],
      "id": 900062,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/meghna_raj_hw6gdw.jpg",
      "release_date": "2016-01-13",
      "title": "Meghna Raj",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/sudharani_pbxqwv.jpg", 
      "genre_ids": [2],
      "id": 900063,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/sudharani_pbxqwv.jpg",
      "release_date": "2016-01-13",
      "title": "Sudharani",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/harshika_poornachha_bpgtgu.jpg", 
      "genre_ids": [2],
      "id": 900064,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/harshika_poornachha_bpgtgu.jpg",
      "release_date": "2016-01-13",
      "title": "Harshika Pornaccha",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/shwtha_changappa_s3djus.jpg", 
      "genre_ids": [2],
      "id": 900065,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/shwtha_changappa_s3djus.jpg",
      "release_date": "2016-01-13",
      "title": "Shwetha Changappa",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/bhavan_rao_tiwwqf.jpg", 
      "genre_ids": [2],
      "id": 900066,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/bhavan_rao_tiwwqf.jpg",
      "release_date": "2016-01-13",
      "title": "Bavana Rao",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/ranjani_ragavan_ac9uk8.jpg", 
      "genre_ids": [2],
      "id": 900067,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/ranjani_ragavan_ac9uk8.jpg",
      "release_date": "2016-01-13",
      "title": "Ranjani Ragavan",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/shvithi_shetty_zxlrj8.jpg", 
      "genre_ids": [2],
      "id": 900068,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/shvithi_shetty_zxlrj8.jpg",
      "release_date": "2016-01-13",
      "title": "Ashvitha Shetty",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/shwetha_srivatsava_uzo2jx.jpg", 
      "genre_ids": [2],
      "id": 900069,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/shwetha_srivatsava_uzo2jx.jpg",
      "release_date": "2016-01-13",
      "title": "Shwetha Srivatsava",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/thara_anuradhar_npcfql.jpg", 
      "genre_ids": [2],
      "id": 900070,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/thara_anuradhar_npcfql.jpg",
      "release_date": "2016-01-13",
      "title": "Thara",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/shruthi_krishna_x234fx.jpg", 
      "genre_ids": [2],
      "id": 900071,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/shruthi_krishna_x234fx.jpg",
      "release_date": "2016-01-13",
      "title": "Shruthi",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/ragini_a7cxx5.jpg", 
      "genre_ids": [2],
      "id": 900072,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/ragini_a7cxx5.jpg",
      "release_date": "2016-01-13",
      "title": "Ragini",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/thanisha_kuppanada_gvgcka.jpg", 
      "genre_ids": [2],
      "id": 900073,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/thanisha_kuppanada_gvgcka.jpg",
      "release_date": "2016-01-13",
      "title": "Thanisha",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/niveditah_gowda_zojw4d.jpg", 
      "genre_ids": [2],
      "id": 900074,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/niveditah_gowda_zojw4d.jpg",
      "release_date": "2016-01-13",
      "title": "Niveditha",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/anuratdha_bhat_a18nxu.jpg", 
      "genre_ids": [3],
      "id": 900075,
      "media_type": "movie",
      "position": "singer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/anuratdha_bhat_a18nxu.jpg",
      "release_date": "2016-01-13",
      "title": "Anuradha bhat",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/darling_krishna_aavf1x.jpg", 
      "genre_ids": [1],
      "id": 900076,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/darling_krishna_aavf1x.jpg",
      "release_date": "2016-01-13",
      "title": "Darling Krishna",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/rakshith_shetty_czimab.jpg", 
      "genre_ids": [1],
      "id": 900078,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/rakshith_shetty_czimab.jpg",
      "release_date": "2016-01-13",
      "title": "Rakshith shetty",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/dhruva_sarja_lyabvi.jpg", 
      "genre_ids": [1],
      "id": 900079,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/dhruva_sarja_lyabvi.jpg",
      "release_date": "2016-01-13",
      "title": "Dhruva sarja",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/vijay_ragvendrta_x8p0g8.jpg", 
      "genre_ids": [1],
      "id": 900080,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/vijay_ragvendrta_x8p0g8.jpg",
      "release_date": "2016-01-13",
      "title": "Vijay Ragvendra",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/sri_murali_tuujru.jpg", 
      "genre_ids": [1],
      "id": 900081,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/sri_murali_tuujru.jpg",
      "release_date": "2016-01-13",
      "title": "Sri murali",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/rajvendra_rajkumar_ekzwef.jpg", 
      "genre_ids": [1],
      "id": 900082,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/rajvendra_rajkumar_ekzwef.jpg",
      "release_date": "2016-01-13",
      "title": "Ragavendra rajkumar",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/indrajith_lankesh_iv1dln.jpg", 
      "genre_ids": [1],
      "id": 900083,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/indrajith_lankesh_iv1dln.jpg",
      "release_date": "2016-01-13",
      "title": "Indrajith Lankesh",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/ravichandran_bsfrx1.jpg", 
      "genre_ids": [1],
      "id": 900084,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/ravichandran_bsfrx1.jpg",
      "release_date": "2016-01-13",
      "title": "Ravichandran",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/kirik_keerthy_nftkok.jpg", 
      "genre_ids": [4],
      "id": 900085,
      "media_type": "movie",
      "position": "anchor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/kirik_keerthy_nftkok.jpg",
      "release_date": "2016-01-13",
      "title": "kirik keerthy",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/vicky_pedia_dhrhxj.jpg", 
      "genre_ids": [9],
      "id": 900086,
      "media_type": "movie",
      "position": "comedy_actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/vicky_pedia_dhrhxj.jpg",
      "release_date": "2016-01-13",
      "title": "Vicky Pedia",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/Rajesh_krishna_ydxcpm.jpg", 
      "genre_ids": [3],
      "id": 900087,
      "media_type": "movie",
      "position": "singer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/Rajesh_krishna_ydxcpm.jpg",
      "release_date": "2016-01-13",
      "title": "Rajesh krishna",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/priyanka_upendra_bllqj2.jpg", 
      "genre_ids": [2],
      "id": 900088,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/priyanka_upendra_bllqj2.jpg",
      "release_date": "2016-01-13",
      "title": "Priyanka Upendra",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/arjun_janaya_khcchp.jpg", 
      "genre_ids": [3],
      "id": 900089,
      "media_type": "movie",
      "position": "singer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/arjun_janaya_khcchp.jpg",
      "release_date": "2016-01-13",
      "title": "Arjun Janya",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/Sanjith_Hegde__goq5xz.jpg", 
      "genre_ids": [3],
      "id": 900090,
      "media_type": "movie",
      "position": "singer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/Sanjith_Hegde__goq5xz.jpg",
      "release_date": "2016-01-13",
      "title": "Sanjeeth Hegde",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/divya_ramachandra_fg1giv.jpg", 
      "genre_ids": [3],
      "id": 900091,
      "media_type": "movie",
      "position": "singer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/divya_ramachandra_fg1giv.jpg",
      "release_date": "2016-01-13",
      "title": "Divya Ramachandra",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/ananya_bhat_oxqxes.jpg", 
      "genre_ids": [3],
      "id": 900092,
      "media_type": "movie",
      "position": "singer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/ananya_bhat_oxqxes.jpg",
      "release_date": "2016-01-13",
      "title": "Ananya Bhat",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/vasita_simha_gpx7xs.jpg", 
      "genre_ids": [1],
      "id": 900093,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/vasita_simha_gpx7xs.jpg",
      "release_date": "2016-01-13",
      "title": "Vasista Simha",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/vasita_simha_gpx7xs.jpg", 
      "genre_ids": [9],
      "id": 900094,
      "media_type": "movie",
      "position": "comedy_actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/Sanjith_Hegde__goq5xz.jpg",
      "release_date": "2016-01-13",
      "title": "Danish Seit",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/Sanjith_Hegde__goq5xz.jpg", 
      "genre_ids": [9],
      "id": 900095,
      "media_type": "movie",
      "position": "comedy_actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/Sanjith_Hegde__goq5xz.jpg",
      "release_date": "2016-01-13",
      "title": "Raj B Shetty",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/Sanjith_Hegde__goq5xz.jpg", 
      "genre_ids": [9],
      "id": 900096,
      "media_type": "movie",
      "position": "comedy_actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/Sanjith_Hegde__goq5xz.jpg",
      "release_date": "2016-01-13",
      "title": "Varthur Santhosh",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/sangeetha_sringeri_dy5kzs.jpg", 
      "genre_ids": [2],
      "id": 900097,
      "media_type": "movie",
      "position": "actress",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/sangeetha_sringeri_dy5kzs.jpg",
      "release_date": "2016-01-13",
      "title": "Sangeetha Sringeri",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/ganesh_karanth_up0bhb.jpg", 
      "genre_ids": [3],
      "id": 900098,
      "media_type": "movie",
      "position": "singer",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/ganesh_karanth_up0bhb.jpg",
      "release_date": "2016-01-13",
      "title": "Ganesh Karanth",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/15-astonishing-facts-about-darshan-thoogudeepa-1697770170_rwfhpb.jpg", 
      "genre_ids": [3],
      "id": 900099,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/15-astonishing-facts-about-darshan-thoogudeepa-1697770170_rwfhpb.jpg",
      "release_date": "2016-01-13",
      "title": "Darshan",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    },
    {
      "adult": false,
      "backdrop_path": "/dananj_zv7zjz.jpg", 
      "genre_ids": [3],
      "id": 900100,
      "media_type": "movie",
      "position": "actor",
      "original_language": "en",
      "original_title": "13 Hours: The Secret Soldiers of Benghazi",
      "overview": "An American Ambassador is killed during an attack at a U.S. compound in Libya as a security team struggles to make sense out of the chaos.",
      "popularity": 1430.84,
      "poster_path": "/dananj_zv7zjz.jpg",
      "release_date": "2016-01-13",
      "title": "Dananjaya",
      "video": false,
      "vote_average": 7.1,
      "vote_count": 2427
    }
    








  ],
  total_pages: 1000,
  total_results: 20000
};




    const [endpoint, setEndpoint] = useState("actor"); // Default endpoint
    const [data, setData] = useState([]); // Initialize as empty array
    const [loading, setLoading] = useState(true);
    const [id, setid] = useState(0)

    useEffect(() => {
        // Filter data based on endpoint
        const filteredData = [];
        for (let item of sampleData1.results) {
            if (item.position === endpoint) 
              {
                console.log(endpoint)
                filteredData.push(item);
                setid(item.id);
                console.log(item.id)
              }
        }
        setData(filteredData); // Update data state with filtered results
        setLoading(false); // Set loading state to false once data is filtered
    }, [endpoint]); // Trigger effect whenever endpoint changes

    // Handle tab click event
    const handlePopularityClick = (position) => {
        setEndpoint(position);
      // Update endpoint state with selected position
    };

    return (
        <div className="carouselSection">
            <h5 className="carouselSection-text">
            Pick the perfect star for your event! Our top priority is your satisfaction, and we're eager to exceed your expectations, guided by your feedback.
            </h5>
            <ContentWrapper className="contentWrapper">
                <div className="tabs">
                    {/* Tab for Actor */}
                    <div className={`tab ${endpoint === "actor" ? "active" : ""}`} onClick={() => handlePopularityClick("actor")}>{/*<HiUser /> */} Actor</div>
                    <div className={`tab ${endpoint === "actress" ? "active" : ""}`} onClick={() => handlePopularityClick("actress")}>{/*<FaFemale /> */} Actress</div>
                    
                    <div className={`tab ${endpoint === "sports" ? "active" : ""}`} onClick={() => handlePopularityClick("sports")}>{/*<MdOutlineSportsCricket />  */}Sports</div>
                    {/* Tab for Comedy Actor */}
                    <div className={`tab ${endpoint === "enterprenuer" ? "active" : ""}`} onClick={() => handlePopularityClick("enterprenuer")}>{/* <FaBusinessTime /> */}Enterprenuer</div>
                    <div className={`tab ${endpoint === "comedy_actor" ? "active" : ""}`} onClick={() => handlePopularityClick("comedy_actor")}>{/*<GiCardJoker /> */} Comedian</div>
                    
                    {/* Add more tabs as needed */}


                    <div className={`tab ${endpoint === "singer" ? "active" : ""}`} onClick={() => handlePopularityClick("singer")}>{/*<GiLoveSong /> */} Singer</div>
                    


              
                    <div className={`tab ${endpoint === "anchor" ? "active" : ""}`} onClick={() => handlePopularityClick("anchor")}>{/* <SlPeople />*/} Anchor</div>
                    
              
      
                    <div className={`tab ${endpoint === "influencer" ? "active" : ""}`} onClick={() => handlePopularityClick("influencer")}>{/* <HiOutlineSwitchHorizontal />*/} Influencer</div>
                
                    <div className={`tab ${endpoint === "fitness" ? "active" : ""}`} onClick={() => handlePopularityClick("fitness")}>{/* <HiOutlineUserGroup /> */}Fitness</div>

                    <div className={`tab ${endpoint === "dj" ? "active" : ""}`} onClick={() => handlePopularityClick("dj")}>{/*<HiOutlineUserGroup /> */} DJ</div>
                    <div className={`tab ${endpoint === "Mentalist" ? "active" : ""}`} onClick={() => handlePopularityClick("Mentalist")}>{/*<HiOutlineUserGroup /> */} Mentalist</div>
                    <div className={`tab ${endpoint === "Magician" ? "active" : ""}`} onClick={() => handlePopularityClick("Magician")}>{/*<HiOutlineUserGroup /> */} Magician</div>
                    <div className={`tab ${endpoint === "others" ? "active" : ""}`} onClick={() => handlePopularityClick("others")}>{/*<HiOutlineUserGroup /> */} others</div>

         
                </div>
                
                {/* Placeholder for SwitchTabs component (dummy implementation) */}
                <SwitchTabs
                    data={["Day", "Week"]}
                    onTabChange={(tab) => console.log(tab === "Day" ? "day" : "week")}
                />
            </ContentWrapper>

            {/* Render the Carousel component */}
            <Carousel data={data} loading={loading} endpoint={endpoint} id={id} />
        </div>
    );
};

export default Trending;
